/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Sonnet 4.6 (1M context)

import { dump } from 'js-yaml';
import React, { useCallback, useEffect, useRef } from 'react';

import { useTheme } from '@/contexts/ThemeContext';
import { DevWorkspaceStatus } from '@/services/helpers/types';
import { Workspace } from '@/services/workspace-adapter';
import { selectAiAgentRegistryEnabled, selectDefaultAgent } from '@/store/AiAgentRegistry';
import { selectDevWorkspaceSchema } from '@/store/DevWorkspaceSchema';
import { useAppDispatch, useAppSelector } from '@/store/hooks';
import {
  actionCreators,
  AgentPodPhase,
  AgentPodStatus,
  clearAgentTerminalUrl,
} from '@/store/LocalDevfiles';
import { selectAgentPodStatuses, selectAgentTerminalUrl } from '@/store/LocalDevfiles/selectors';
import { devWorkspacesActionCreators } from '@/store/Workspaces/devWorkspaces';

// Lazy-load LoaderAgentPanel to break circular dependency through the plugin
// component tree (AgentPanel → AgentTerminal → ... → store → entry module).
const LazyLoaderAgentPanel = React.lazy(() => import('@/components/LoaderAgentPanel'));

const MAX_HEARTBEAT_ERRORS = 6;
const MAX_TERMINAL_POLL_ERRORS = 12;
const HEARTBEAT_INTERVAL_MS = 60_000;
const TERMINAL_POLL_INTERVAL_MS = 3_000;

interface Props {
  workspace: unknown;
  isActive: boolean;
}

function getWorkspaceContent(ws: Workspace): string {
  try {
    const template = (ws.ref as { spec?: { template?: unknown } }).spec?.template;
    return template ? dump(template) : '';
  } catch {
    return '';
  }
}

// Generated by Claude Sonnet 4.6 (1M context)
export default function LoaderAgentPanelTab(props: Props): React.ReactElement | null {
  const { workspace } = props;
  const { isDarkTheme } = useTheme();
  const dispatch = useAppDispatch();

  const agentPodStatuses = useAppSelector(selectAgentPodStatuses);
  const agentTerminalUrl = useAppSelector(selectAgentTerminalUrl);
  const agentEnabled = useAppSelector(selectAiAgentRegistryEnabled);
  const defaultAgent = useAppSelector(selectDefaultAgent);
  const devWorkspaceSchema = useAppSelector(selectDevWorkspaceSchema);

  // Per-instance agent ID — lives in a ref so each mounted tab has its own ID
  // without polluting module scope (which broke when multiple tabs were open).
  const tabAgentInstanceIdRef = useRef<string | undefined>(undefined);

  const terminalPollTimerRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const heartbeatTimerRef = useRef<ReturnType<typeof setInterval> | undefined>(undefined);
  const heartbeatErrorCountRef = useRef(0);
  const terminalPollErrorCountRef = useRef(0);

  // Keep stable references to redux action dispatchers
  const startAgent = useCallback(
    (...args: Parameters<typeof actionCreators.startAgent>) =>
      dispatch(actionCreators.startAgent(...args)),
    [dispatch],
  );
  const stopAgent = useCallback(
    (...args: Parameters<typeof actionCreators.stopAgent>) =>
      dispatch(actionCreators.stopAgent(...args)),
    [dispatch],
  );
  const fetchAgentTerminalUrl = useCallback(
    (...args: Parameters<typeof actionCreators.fetchAgentTerminalUrl>) =>
      dispatch(actionCreators.fetchAgentTerminalUrl(...args)),
    [dispatch],
  );
  const sendHeartbeat = useCallback(
    (...args: Parameters<typeof actionCreators.sendHeartbeat>) =>
      dispatch(actionCreators.sendHeartbeat(...args)),
    [dispatch],
  );
  const dispatchClearAgentTerminalUrl = useCallback(
    () => dispatch(clearAgentTerminalUrl()),
    [dispatch],
  );
  const startWorkspace = useCallback(
    (...args: Parameters<typeof devWorkspacesActionCreators.startWorkspace>) =>
      dispatch(devWorkspacesActionCreators.startWorkspace(...args)),
    [dispatch],
  );
  const stopWorkspace = useCallback(
    (...args: Parameters<typeof devWorkspacesActionCreators.stopWorkspace>) =>
      dispatch(devWorkspacesActionCreators.stopWorkspace(...args)),
    [dispatch],
  );
  const updateWorkspace = useCallback(
    (...args: Parameters<typeof devWorkspacesActionCreators.updateWorkspace>) =>
      dispatch(devWorkspacesActionCreators.updateWorkspace(...args)),
    [dispatch],
  );

  const clearPollTimer = useCallback(() => {
    if (terminalPollTimerRef.current !== undefined) {
      clearTimeout(terminalPollTimerRef.current);
      terminalPollTimerRef.current = undefined;
    }
  }, []);

  const clearHeartbeat = useCallback(() => {
    if (heartbeatTimerRef.current !== undefined) {
      clearInterval(heartbeatTimerRef.current);
      heartbeatTimerRef.current = undefined;
    }
  }, []);

  // Initialise the per-tab agent instance ID on mount (mirrors componentDidMount)
  useEffect(() => {
    if (defaultAgent) {
      const ws = workspace as Workspace | undefined;
      tabAgentInstanceIdRef.current = `${defaultAgent.id}-loader-${ws?.name ?? 'ws'}`;
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // intentionally runs once on mount

  // Cleanup on unmount (mirrors componentWillUnmount)
  useEffect(() => {
    return () => {
      clearPollTimer();
      clearHeartbeat();
      if (tabAgentInstanceIdRef.current) {
        stopAgent(tabAgentInstanceIdRef.current);
        dispatchClearAgentTerminalUrl();
        tabAgentInstanceIdRef.current = undefined;
      }
    };
  }, [clearHeartbeat, clearPollTimer, dispatchClearAgentTerminalUrl, stopAgent]);

  const ws = workspace as Workspace | undefined;
  const prevWsRef = useRef<Workspace | undefined>(ws);

  // Derive agentPodStatus for this instance
  const agentPodStatus: AgentPodStatus | undefined = agentPodStatuses.find(
    s => s.agentId === tabAgentInstanceIdRef.current,
  );

  const sendHeartbeatWithRetry = useCallback(
    async (instanceId: string): Promise<void> => {
      try {
        await sendHeartbeat(instanceId);
        heartbeatErrorCountRef.current = 0;
      } catch (err) {
        console.warn('LoaderAgentPanelTab: heartbeat failed', err);
        heartbeatErrorCountRef.current++;
        if (heartbeatErrorCountRef.current >= MAX_HEARTBEAT_ERRORS) {
          clearHeartbeat();
          if (tabAgentInstanceIdRef.current) {
            stopAgent(tabAgentInstanceIdRef.current);
          }
        }
      }
    },
    [clearHeartbeat, sendHeartbeat, stopAgent],
  );

  // Mirror componentDidUpdate logic for workspace status transition and
  // terminal-URL / heartbeat management.
  useEffect(() => {
    const prevWs = prevWsRef.current;
    prevWsRef.current = ws;

    // Stop the agent automatically when the workspace finishes starting
    if (
      prevWs?.status !== DevWorkspaceStatus.RUNNING &&
      ws?.status === DevWorkspaceStatus.RUNNING &&
      tabAgentInstanceIdRef.current
    ) {
      clearPollTimer();
      clearHeartbeat();
      stopAgent(tabAgentInstanceIdRef.current);
      dispatchClearAgentTerminalUrl();
      tabAgentInstanceIdRef.current = undefined;
      return;
    }

    // --- fetchTerminalUrlIfNeeded ---
    const isRunning = agentPodStatus?.phase === AgentPodPhase.RUNNING && agentPodStatus?.ready;

    if (isRunning && !agentTerminalUrl && terminalPollTimerRef.current === undefined) {
      // startTerminalPolling
      terminalPollErrorCountRef.current = 0;
      const poll = async () => {
        const currentAgentPodStatus = agentPodStatuses.find(
          s => s.agentId === tabAgentInstanceIdRef.current,
        );
        const stillRunning =
          currentAgentPodStatus?.phase === AgentPodPhase.RUNNING && currentAgentPodStatus?.ready;

        // Read agentTerminalUrl from store via a stable closure variable that
        // is refreshed every render (captured at effect run time).
        if (!stillRunning || agentTerminalUrl) {
          clearPollTimer();
          return;
        }
        if (defaultAgent && tabAgentInstanceIdRef.current) {
          try {
            await fetchAgentTerminalUrl(tabAgentInstanceIdRef.current, defaultAgent.terminalPort);
            terminalPollErrorCountRef.current = 0;
          } catch (err) {
            console.warn('LoaderAgentPanelTab: fetchAgentTerminalUrl failed', err);
            terminalPollErrorCountRef.current++;
            if (terminalPollErrorCountRef.current >= MAX_TERMINAL_POLL_ERRORS) {
              clearPollTimer();
              return;
            }
          }
        }
        terminalPollTimerRef.current = setTimeout(poll, TERMINAL_POLL_INTERVAL_MS);
      };
      poll();
    }

    if (agentTerminalUrl) {
      clearPollTimer();
    }

    if (!isRunning) {
      clearPollTimer();
      if (agentTerminalUrl) {
        dispatchClearAgentTerminalUrl();
      }
    }

    // --- manageHeartbeat ---
    if (isRunning && tabAgentInstanceIdRef.current && heartbeatTimerRef.current === undefined) {
      const instanceId = tabAgentInstanceIdRef.current;
      heartbeatErrorCountRef.current = 0;
      sendHeartbeatWithRetry(instanceId);
      heartbeatTimerRef.current = setInterval(() => {
        sendHeartbeatWithRetry(instanceId);
      }, HEARTBEAT_INTERVAL_MS);
    }

    if (!isRunning && heartbeatTimerRef.current !== undefined) {
      clearHeartbeat();
    }
  });

  if (!ws || !agentEnabled) {
    return null;
  }

  return (
    <React.Suspense fallback={null}>
      <LazyLoaderAgentPanel
        agentPodStatus={agentPodStatus}
        agentTerminalUrl={agentTerminalUrl}
        agentInstanceId={tabAgentInstanceIdRef.current}
        agentInitCommand={defaultAgent?.initCommand}
        agentName={defaultAgent?.name}
        agentDescription={defaultAgent?.description}
        isDarkTheme={isDarkTheme}
        workspaceName={ws.name}
        workspaceNamespace={ws.namespace}
        workspaceContent={getWorkspaceContent(ws)}
        workspaceStatus={ws.status as DevWorkspaceStatus}
        devWorkspaceSchema={devWorkspaceSchema}
        agentEnabled={agentEnabled}
        onStartWorkspace={() => {
          if (ws?.ref) {
            startWorkspace(ws.ref).catch(console.error);
          }
        }}
        onStopWorkspace={() => {
          if (ws?.ref) {
            stopWorkspace(ws.ref).catch(console.error);
          }
        }}
        onSaveWorkspace={async () => {
          if (ws?.ref) {
            const updated = { ...ws.ref };
            await updateWorkspace(updated);
          }
        }}
        onStartAgent={async () => {
          if (defaultAgent && tabAgentInstanceIdRef.current) {
            await startAgent(defaultAgent, tabAgentInstanceIdRef.current);
          }
        }}
        onStopAgent={() => {
          if (tabAgentInstanceIdRef.current) {
            stopAgent(tabAgentInstanceIdRef.current);
          }
        }}
      />
    </React.Suspense>
  );
}
