/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import { api, helpers } from '@eclipse-che/common';
import * as k8s from '@kubernetes/client-node';

import { STRATEGIC_MERGE_PATCH_OPTIONS } from '@/devworkspaceClient/services/helpers/patchOptions';
import { isLocalRun } from '@/localRun';
import { getKubeConfig } from '@/routes/api/helpers/getDevWorkspaceClient';
import {
  AGENT_DEFAULT_CPU_REQUEST,
  AGENT_DEFAULT_MEMORY_REQUEST,
  AGENT_LABEL_AGENT_ID,
  AGENT_LABEL_COMPONENT,
  AGENT_TTL_MINUTES,
  BLOCKED_ENV_NAMES,
  DW_MOUNT_AS,
  DW_MOUNT_LABEL,
  DW_MOUNT_PATH,
  HEARTBEAT_ANNOTATION,
  MAX_AGENT_PODS_PER_USER,
  PERIODIC_CLEANUP_INTERVAL_MS,
  TOKEN_MOUNT_PATH,
  TOKEN_SECRET_VOLUME,
} from './agentPodConstants';
import {
  agentLabels,
  agentPodName,
  agentServiceName,
  agentTokenSecretName,
  isTerminalPhase,
  normalizeAgentId,
} from './agentPodHelpers';
import { KubeConfigProvider } from '@/services/kubeclient/kubeConfigProvider';
import { logger } from '@/utils/logger';

export { normalizeAgentId } from './agentPodHelpers';

export interface AgentPodStatus {
  agentId: string;
  name: string;
  phase: string;
  ready: boolean;
  serviceUrl: string | undefined;
}

interface AgentConfig {
  image: string;
  tag: string;
  memoryLimit: string;
  cpuLimit: string;
  terminalPort: number;
  env: api.AiAgentEnvVar[];
}

interface DevWorkspaceMounts {
  volumes: k8s.V1Volume[];
  volumeMounts: k8s.V1VolumeMount[];
  envFrom: k8s.V1EnvFromSource[];
}

function getCoreV1Api(token: string): k8s.CoreV1Api {
  const kubeConfig = getKubeConfig(token);
  return kubeConfig.makeApiClient(k8s.CoreV1Api);
}

async function discoverDevWorkspaceMounts(
  coreV1Api: k8s.CoreV1Api,
  namespace: string,
): Promise<DevWorkspaceMounts> {
  const volumes: k8s.V1Volume[] = [];
  const volumeMounts: k8s.V1VolumeMount[] = [];
  const envFrom: k8s.V1EnvFromSource[] = [];

  try {
    const secrets = await coreV1Api.listNamespacedSecret({
      namespace,
      labelSelector: `${DW_MOUNT_LABEL}=true`,
    });

    for (const secret of secrets.items) {
      const name = secret.metadata?.name;
      if (!name) continue;

      const mountAs = secret.metadata?.annotations?.[DW_MOUNT_AS];
      const mountPath = secret.metadata?.annotations?.[DW_MOUNT_PATH];

      if (mountAs === 'file' && mountPath) {
        const volumeName = `secret-${name}`;
        volumes.push({ name: volumeName, secret: { secretName: name } });
        volumeMounts.push({ name: volumeName, mountPath, readOnly: true });
      } else if (mountAs === 'env') {
        envFrom.push({ secretRef: { name } });
      }
    }
  } catch (e) {
    logger.warn(e, 'Failed to discover DevWorkspace-mountable secrets');
  }

  try {
    const configMaps = await coreV1Api.listNamespacedConfigMap({
      namespace,
      labelSelector: `${DW_MOUNT_LABEL}=true`,
    });

    for (const cm of configMaps.items) {
      const name = cm.metadata?.name;
      if (!name) continue;

      const mountAs = cm.metadata?.annotations?.[DW_MOUNT_AS];
      const mountPath = cm.metadata?.annotations?.[DW_MOUNT_PATH];

      if (mountAs === 'env') {
        envFrom.push({ configMapRef: { name } });
      } else if (mountAs === 'file' && mountPath) {
        const volumeName = `cm-${name}`;
        volumes.push({ name: volumeName, configMap: { name } });
        volumeMounts.push({ name: volumeName, mountPath, readOnly: true });
      }
    }
  } catch (e) {
    logger.warn(e, 'Failed to discover DevWorkspace-mountable configmaps');
  }

  return { volumes, volumeMounts, envFrom };
}

export async function createAgentPod(
  token: string,
  namespace: string,
  agentId: string,
  config: AgentConfig,
): Promise<AgentPodStatus> {
  const coreV1Api = getCoreV1Api(token);
  const podName = agentPodName(agentId);
  const svcName = agentServiceName(agentId);
  const secretName = agentTokenSecretName(agentId);
  const labels = agentLabels(agentId);

  await cleanupExpiredAgentPods(token, namespace);

  const existing = await findAgentPod(coreV1Api, namespace, agentId);
  if (existing) {
    const phase = existing.status?.phase || 'Unknown';
    if (isTerminalPhase(phase)) {
      const existingName = existing.metadata?.name;
      if (existingName) {
        await coreV1Api.deleteNamespacedPod({ name: existingName, namespace });
      }
    } else {
      return podToStatus(existing, agentId, namespace, config.terminalPort);
    }
  }

  const normalized = normalizeAgentId(agentId);
  const allPodsForAgent = await coreV1Api.listNamespacedPod({
    namespace,
    labelSelector: `${AGENT_LABEL_AGENT_ID}=${normalized}`,
  });
  const terminating = allPodsForAgent.items.find(p => !!p.metadata?.deletionTimestamp);
  if (terminating) {
    const terminatingName = terminating.metadata?.name;
    if (terminatingName) {
      try {
        await coreV1Api.deleteNamespacedPod({
          name: terminatingName,
          namespace,
          body: { gracePeriodSeconds: 0 },
        });
      } catch {
        // ignore — pod may have already been deleted
      }
    }
  }

  const activePods = await coreV1Api.listNamespacedPod({
    namespace,
    labelSelector: `${AGENT_LABEL_COMPONENT}=ai-agent`,
  });
  const runningCount = activePods.items.filter(
    p =>
      !p.metadata?.deletionTimestamp &&
      p.status?.phase !== 'Failed' &&
      p.status?.phase !== 'Succeeded',
  ).length;
  if (runningCount >= MAX_AGENT_PODS_PER_USER) {
    throw Object.assign(
      new Error(
        `Maximum number of agent pods (${MAX_AGENT_PODS_PER_USER}) reached. Stop an existing agent before starting a new one.`,
      ),
      { statusCode: 409 },
    );
  }

  const dwMounts = await discoverDevWorkspaceMounts(coreV1Api, namespace);
  const now = new Date().toISOString();

  const kubeConfig = getKubeConfig(token);
  const kubeApiUrl = kubeConfig.getCurrentCluster()?.server || '';

  await createOrReplaceTokenSecret(coreV1Api, namespace, secretName, token, labels);

  const allVolumes: k8s.V1Volume[] = [
    ...dwMounts.volumes,
    { name: TOKEN_SECRET_VOLUME, secret: { secretName } },
    { name: 'tmp-dir', emptyDir: {} },
  ];
  const allVolumeMounts: k8s.V1VolumeMount[] = [
    ...dwMounts.volumeMounts,
    { name: TOKEN_SECRET_VOLUME, mountPath: TOKEN_MOUNT_PATH, readOnly: true },
    { name: 'tmp-dir', mountPath: '/tmp' },
  ];

  const pod = await coreV1Api.createNamespacedPod({
    namespace,
    body: {
      metadata: {
        name: podName,
        namespace,
        labels,
        annotations: {
          'che.eclipse.org/ai-agent-id': agentId,
          [HEARTBEAT_ANNOTATION]: now,
        },
      },
      spec: {
        automountServiceAccountToken: false,
        volumes: allVolumes,
        containers: [
          {
            name: 'agent',
            image: `${config.image}:${config.tag}`,
            imagePullPolicy: 'IfNotPresent',
            ports: [{ containerPort: config.terminalPort, name: 'terminal', protocol: 'TCP' }],
            resources: {
              limits: { memory: config.memoryLimit, cpu: config.cpuLimit },
              requests: { memory: AGENT_DEFAULT_MEMORY_REQUEST, cpu: AGENT_DEFAULT_CPU_REQUEST },
            },
            env: [
              ...config.env.filter(e => !BLOCKED_ENV_NAMES.has(e.name)),
              { name: 'AGENT_NAMESPACE', value: namespace },
              { name: 'KUBERNETES_API_URL', value: kubeApiUrl },
              { name: 'CHE_USER_TOKEN_FILE', value: `${TOKEN_MOUNT_PATH}/token` },
            ],
            envFrom: dwMounts.envFrom.length > 0 ? dwMounts.envFrom : undefined,
            volumeMounts: allVolumeMounts,
            securityContext: {
              allowPrivilegeEscalation: false,
              // runAsUser omitted — OpenShift assigns a UID from the namespace range
              runAsNonRoot: true,
              capabilities: { drop: ['ALL'] },
              // seccompProfile omitted — restricted SCC forbids the annotation
            },
          },
        ],
        restartPolicy: 'Never',
        terminationGracePeriodSeconds: 5,
      },
    },
  });

  const podUid = pod.metadata?.uid;
  if (!podUid) {
    throw new Error(`Created pod ${podName} has no UID; cannot set owner reference on secret`);
  }
  await setSecretOwnerReference(coreV1Api, namespace, secretName, podName, podUid);

  await coreV1Api.createNamespacedService({
    namespace,
    body: {
      metadata: {
        name: svcName,
        namespace,
        labels,
        ownerReferences: [{ apiVersion: 'v1', kind: 'Pod', name: podName, uid: podUid }],
      },
      spec: {
        type: 'ClusterIP',
        selector: { [AGENT_LABEL_AGENT_ID]: normalizeAgentId(agentId) },
        ports: [
          {
            name: 'terminal',
            port: config.terminalPort,
            targetPort: config.terminalPort,
            protocol: 'TCP',
          },
        ],
      },
    },
  });

  return podToStatus(pod, agentId, namespace, config.terminalPort);
}

export async function getAgentPodStatus(
  token: string,
  namespace: string,
  agentId: string,
  terminalPort = 8080,
): Promise<AgentPodStatus | undefined> {
  const coreV1Api = getCoreV1Api(token);
  const pod = await findAgentPod(coreV1Api, namespace, agentId);
  if (!pod) return undefined;
  return podToStatus(pod, agentId, namespace, terminalPort);
}

export async function deleteAgentPod(
  token: string,
  namespace: string,
  agentId: string,
): Promise<void> {
  const coreV1Api = getCoreV1Api(token);
  const pod = await findAgentPod(coreV1Api, namespace, agentId);
  if (pod?.metadata?.name) {
    await coreV1Api.deleteNamespacedPod({
      name: pod.metadata.name,
      namespace,
      body: { gracePeriodSeconds: 5 },
    });
  }

  const secretName = agentTokenSecretName(agentId);
  try {
    await coreV1Api.deleteNamespacedSecret({ name: secretName, namespace });
  } catch (e: unknown) {
    if (helpers.errors.isKubeClientError(e) && e.code === 404) {
      // Already deleted
    } else {
      logger.warn(e, 'Failed to delete agent token secret: %s', secretName);
    }
  }
}

export async function heartbeatAgentPod(
  token: string,
  namespace: string,
  agentId: string,
): Promise<void> {
  const coreV1Api = getCoreV1Api(token);
  const pod = await findAgentPod(coreV1Api, namespace, agentId);
  if (!pod?.metadata?.name) return;

  const now = new Date().toISOString();
  await coreV1Api.patchNamespacedPod(
    {
      name: pod.metadata.name,
      namespace,
      body: { metadata: { annotations: { [HEARTBEAT_ANNOTATION]: now } } },
    },
    STRATEGIC_MERGE_PATCH_OPTIONS,
  );
}

export async function cleanupExpiredAgentPods(token: string, namespace: string): Promise<string[]> {
  const coreV1Api = getCoreV1Api(token);
  const pods = await coreV1Api.listNamespacedPod({
    namespace,
    labelSelector: `${AGENT_LABEL_COMPONENT}=ai-agent`,
  });

  const now = Date.now();
  const ttlMs = AGENT_TTL_MINUTES * 60 * 1000;
  const deleted: string[] = [];

  for (const pod of pods.items) {
    const heartbeat = pod.metadata?.annotations?.[HEARTBEAT_ANNOTATION];
    if (!heartbeat) continue;

    const lastBeat = new Date(heartbeat).getTime();
    if (now - lastBeat > ttlMs) {
      const name = pod.metadata?.name;
      if (!name) continue;
      logger.info('Cleaning up expired agent pod: %s (last heartbeat: %s)', name, heartbeat);
      try {
        await coreV1Api.deleteNamespacedPod({ name, namespace, body: { gracePeriodSeconds: 5 } });
        deleted.push(name);
      } catch (e) {
        logger.error(e, 'Failed to delete expired agent pod: %s', name);
      }
    }
  }
  return deleted;
}

let periodicCleanupTimer: ReturnType<typeof setInterval> | undefined;

export function startPeriodicAgentCleanup(getToken: () => string): void {
  if (periodicCleanupTimer) return;

  periodicCleanupTimer = setInterval(async () => {
    try {
      const token = getToken();
      const coreV1Api = getCoreV1Api(token);
      const allPods = await coreV1Api.listPodForAllNamespaces({
        labelSelector: `${AGENT_LABEL_COMPONENT}=ai-agent`,
      });

      const now = Date.now();
      const ttlMs = AGENT_TTL_MINUTES * 60 * 1000;

      for (const pod of allPods.items) {
        const heartbeat = pod.metadata?.annotations?.[HEARTBEAT_ANNOTATION];
        if (!heartbeat) continue;

        const lastBeat = new Date(heartbeat).getTime();
        if (now - lastBeat > ttlMs) {
          const name = pod.metadata?.name;
          const podNamespace = pod.metadata?.namespace;
          if (!name || !podNamespace) continue;
          logger.info('Periodic cleanup: deleting expired agent pod %s/%s', podNamespace, name);
          try {
            await coreV1Api.deleteNamespacedPod({
              name,
              namespace: podNamespace,
              body: { gracePeriodSeconds: 5 },
            });
          } catch (e) {
            logger.error(e, 'Periodic cleanup: failed to delete pod %s/%s', podNamespace, name);
          }
        }
      }
    } catch (e) {
      logger.warn(e, 'Periodic agent cleanup failed');
    }
  }, PERIODIC_CLEANUP_INTERVAL_MS);

  logger.info(
    'Started periodic agent cleanup (interval: %d min)',
    PERIODIC_CLEANUP_INTERVAL_MS / 60_000,
  );
}

export function stopPeriodicAgentCleanup(): void {
  if (periodicCleanupTimer) {
    clearInterval(periodicCleanupTimer);
    periodicCleanupTimer = undefined;
  }
}

export function getAgentServiceUrl(
  namespace: string,
  agentId: string,
  terminalPort = 8080,
): string {
  const svcName = agentServiceName(agentId);
  return `http://${svcName}.${namespace}.svc:${terminalPort}`;
}

export interface AgentServiceAccess {
  baseUrl: string;
  httpsOptions?: {
    rejectUnauthorized: boolean;
    ca?: string;
  };
}

export function getAgentServiceAccess(
  namespace: string,
  agentId: string,
  terminalPort: number,
): AgentServiceAccess {
  if (isLocalRun()) {
    const kc = new KubeConfigProvider().getSAKubeConfig();
    const cluster = kc.getCurrentCluster();
    if (!cluster) {
      throw new Error('No cluster found in kubeconfig');
    }
    const svcName = agentServiceName(agentId);
    const baseUrl = `${cluster.server}/api/v1/namespaces/${namespace}/services/${svcName}:${terminalPort}/proxy`;
    return {
      baseUrl,
      httpsOptions: {
        rejectUnauthorized: !cluster.skipTLSVerify,
        ca: cluster.caData ? Buffer.from(cluster.caData, 'base64').toString() : undefined,
      },
    };
  }
  return { baseUrl: getAgentServiceUrl(namespace, agentId, terminalPort) };
}

async function findAgentPod(
  coreV1Api: k8s.CoreV1Api,
  namespace: string,
  agentId: string,
): Promise<k8s.V1Pod | undefined> {
  const normalized = normalizeAgentId(agentId);
  const pods = await coreV1Api.listNamespacedPod({
    namespace,
    labelSelector: `${AGENT_LABEL_AGENT_ID}=${normalized}`,
  });
  return pods.items.find(pod => !pod.metadata?.deletionTimestamp);
}

function podToStatus(
  pod: k8s.V1Pod,
  agentId: string,
  namespace: string,
  terminalPort: number,
): AgentPodStatus {
  const phase = pod.status?.phase || 'Unknown';
  const containerReady = pod.status?.containerStatuses?.some(c => c.ready === true) || false;
  const isRunning = phase === 'Running' && containerReady;

  return {
    agentId,
    name: pod.metadata?.name || '',
    phase,
    ready: isRunning,
    serviceUrl: isRunning ? getAgentServiceUrl(namespace, agentId, terminalPort) : undefined,
  };
}

async function createOrReplaceTokenSecret(
  coreV1Api: k8s.CoreV1Api,
  namespace: string,
  secretName: string,
  userToken: string,
  labels: Record<string, string>,
): Promise<void> {
  const secretBody: k8s.V1Secret = {
    metadata: { name: secretName, namespace, labels },
    stringData: { token: userToken },
  };

  try {
    await coreV1Api.createNamespacedSecret({ namespace, body: secretBody });
  } catch (e: unknown) {
    if (helpers.errors.isKubeClientError(e) && e.code === 409) {
      await coreV1Api.replaceNamespacedSecret({ name: secretName, namespace, body: secretBody });
    } else {
      throw e;
    }
  }
}

async function setSecretOwnerReference(
  coreV1Api: k8s.CoreV1Api,
  namespace: string,
  secretName: string,
  podName: string,
  podUid: string,
): Promise<void> {
  await coreV1Api.patchNamespacedSecret(
    {
      name: secretName,
      namespace,
      body: {
        metadata: {
          ownerReferences: [{ apiVersion: 'v1', kind: 'Pod', name: podName, uid: podUid }],
        },
      },
    },
    STRATEGIC_MERGE_PATCH_OPTIONS,
  );
}
