/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by AI Assistant

import { FastifyInstance } from 'fastify';

import { api } from '@eclipse-che/common';

import { baseApiPath } from '@/constants/config';
import { setup, teardown } from '@/utils/appBuilder';

const stubAiRegistry: api.IAiRegistry = {
  providers: [{ id: 'openai', name: 'OpenAI', icon: '' }],
  tools: [],
  defaultAiProviders: ['openai'],
};

jest.mock('@/routes/api/helpers/getDevWorkspaceClient.ts');
jest.mock('@/routes/api/helpers/getServiceAccountToken.ts');
jest.mock('../services/aiRegistryApi', () => ({
  AiRegistryApiService: jest.fn().mockImplementation(() => ({
    get: jest.fn().mockResolvedValue(stubAiRegistry),
  })),
}));

describe('AI Registry Route', () => {
  let app: FastifyInstance;

  beforeEach(async () => {
    app = await setup();
  });

  afterEach(() => {
    teardown(app);
    jest.clearAllMocks();
  });

  test(`GET ${baseApiPath}/ai-registry`, async () => {
    const res = await app.inject().get(`${baseApiPath}/ai-registry`);

    expect(res.statusCode).toEqual(200);
    expect(res.json()).toEqual(stubAiRegistry);
  });
});
