/*
 * Copyright (c) 2018-2025 Red Hat, Inc.
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Red Hat, Inc. - initial API and implementation
 */

// Generated by Claude Opus 4.6

import http from 'node:http';
import https from 'node:https';

import { FastifyReply, FastifyRequest } from 'fastify';

import { AGENT_TERMINAL_THEMES } from '../terminal-themes';
import { AgentServiceAccess } from '../agentPod';
import { buildBridgeScript } from './bridgeScript';

export function proxyToTerminal(
  access: AgentServiceAccess,
  path: string,
  proxyPrefix: string,
  token: string,
  request: FastifyRequest,
  reply: FastifyReply,
): Promise<void> {
  return new Promise((resolve, reject) => {
    const base = access.baseUrl.endsWith('/') ? access.baseUrl : access.baseUrl + '/';
    const relativePath = path.startsWith('/') ? path.slice(1) : path;
    const url = new URL(relativePath, base);
    const isHttps = url.protocol === 'https:';
    const transport = isHttps ? https : http;
    const options: http.RequestOptions = {
      hostname: url.hostname,
      port: url.port || (isHttps ? 443 : 80),
      path: url.pathname + url.search,
      method: request.method,
      headers: {
        host: `${url.hostname}:${url.port || (isHttps ? 443 : 80)}`,
      },
    };
    if (isHttps && access.httpsOptions) {
      (options as https.RequestOptions).rejectUnauthorized = access.httpsOptions.rejectUnauthorized;
      if (access.httpsOptions.ca) {
        (options as https.RequestOptions).ca = access.httpsOptions.ca;
      }
      options.headers = { ...options.headers, Authorization: `Bearer ${token}` };
    }

    const darkThemeJson = JSON.stringify(AGENT_TERMINAL_THEMES.dark);
    const lightThemeJson = JSON.stringify(AGENT_TERMINAL_THEMES.light);

    const proxyReq = transport.request(options, proxyRes => {
      reply.status(proxyRes.statusCode || 200);
      const ct = proxyRes.headers['content-type'];
      if (ct) {
        reply.header('content-type', ct);
      }

      if (ct && ct.includes('text/html')) {
        const chunks: Buffer[] = [];
        proxyRes.on('data', (chunk: Buffer) => chunks.push(chunk));
        proxyRes.on('end', () => {
          let html = Buffer.concat(chunks).toString('utf-8');
          html = html.replace(/href=(["'])\//g, `href=$1${proxyPrefix}/`);
          html = html.replace(/src=(["'])\//g, `src=$1${proxyPrefix}/`);
          html = html.replace(
            '</head>',
            `${buildBridgeScript(darkThemeJson, lightThemeJson)}\n</head>`,
          );
          reply.header('content-length', Buffer.byteLength(html));
          reply.send(html);
          resolve();
        });
      } else {
        reply.send(proxyRes);
        resolve();
      }
    });

    proxyReq.on('error', err => {
      reject(err);
    });

    if (request.raw.readable && !request.body) {
      request.raw.pipe(proxyReq);
    } else {
      proxyReq.end();
    }
  });
}
